### ISSUE TITLE
Release 1.4.1

### ISSUE THREAD

**Issue by blueberry** [gpu/JOCLBlast#14] opened 2018-07-22 10:33 UTC
Hi Marco,

I've just noticed that Cedric has released CLBlast 1.4.1. while we are still at 1.3.0. 

Although there are not many new features of concern to JOCLBlast, there are some performance improvements and bugfixes. Also, it is a good idea to stay up-to-date. 

Do you have any plans regarding the update?

**Comment by gpu** [comment] 2018-07-24 13:47
Sure, I'd also like to avoid falling too far behind with regards to the versions. 

I'd probably schedule two updates, one to 1.4.0 and one to 1.4.1. I've got some time constraints right now. The situation should relax mid of August (although I already have deferred *so* many tasks to "mid of August" that I've basically already piled up an unmanagable amount of work). 

But in the best case, the updates should only consist of running the code generator, and thus, I'll try to squeeze them in, maybe before beginning of next week.

Thanks for the heads-up.

**Comment by gpu** [comment] 2018-08-05 18:10
Too many time constraints, in fact. I'll try to catch up. Sorry for the delay, but the issue is still on the screen.

**Comment by gpu** [comment] 2018-08-06 17:59
I have created the release candidate 

# for 1.4.0 

(not 1.4.1)

at https://github.com/gpu/JOCLBlast/releases/tag/1.4.0-RC00

I could have issued both at the same time, but this way, it may be cleaner. 

@blueberry and @amherag or @milikicn (whoever can provide the Mac binaries)  :

Please make sure to check out the branch `1.4.0` of CLBlast for the compilation. (I haven't yet checked whether there may be incompatibilities between 1.4.0 and 1.4.1, but to be on the safe side).

(Maybe I can also extend the VM at https://github.com/gpu/JOCL#building-on-a-virtual-machine so that I'll be able to build JOCLBlast for Linux here locally, but am not sure when this is likely to happen...)

**Comment by gpu** [comment] 2018-08-22 12:47
Sorry, I know that I'm in a delay here myself, but think that it's appropriate to issue a 
ping @blueberry and @amherag and @milikicn

**Comment by blueberry** [comment] 2018-08-22 12:51
I'm sorry for the delay. I had a lot of other work, and this task was being delayed further and further. I haven't forgot, I just didn't come around to do it. I'll see to find some time in a few days to do this build.
Thanks for the reminder.

**Comment by blueberry** [comment] 2018-08-22 12:54
@gpu Do we even need 1.4.0? I guess that whoever uses JOCLBlast will upgrade to the latest version right away (1.4.1) and 1.4.0 would be eventually useful for backward compatibility, which is not very likely since no one had the opportunity to use it and depend on it yet since it hasn't been built yet...

**Comment by gpu** [comment] 2018-08-22 16:04
Well, I thought it would be nice to have a matching JOCLBlast version for each CLBlast version. Since it's a `x.x.1` difference, it should not be so critical. If you think that it's not worthwhile to have two releases, I can do the update to 1.4.1 (it should, however, be tagged and versioned accordingly).

**Comment by blueberry** [comment] 2018-08-22 16:26
@gpu I myself can do two releases, since it's not that much hassle on Linux, but @milikicn already reported difficulties with even building/installing CLBlast 1.4.0 on osx. I don't know whether you remember, but even for the previous version, there were problems with getting self-built CLBlast to work on osx, so he had to use the one with brew. That, unfortunately, created the dependency to the brew's installation of clblast for all osx users (which is a bit awkward, but at least works). Now he reported that brew comes with 1.4.1 and that he couldn't make 1.4.0 work at all...

**Comment by milikicn** [comment] 2018-08-22 20:40
@gpu Sorry for the delay. Here is the build for the 1.4.0 release.

[jocl-blast-1.4.0-SNAPSHOT.zip](https://github.com/gpu/JOCLBlast/files/2311929/jocl-blast-1.4.0-SNAPSHOT.zip)

**Comment by milikicn** [comment] 2018-08-22 21:07
Putting here (for the refference) the list of commands that worked for me to build JOCLBlast on OS X (1.4.0 version of both CLBlast and JOCLBlast). Not sure if the issue #13 that @amherag reported is still valid as I am able to build it from scratch.

> mkdir JOCLBlastBuld && cd JOCLBlastBuld
> git clone https://github.com/gpu/JOCLCommon.git
> git clone https://github.com/gpu/JOCLBlast.git
> cd JOCLBlast/
> git checkout tags/1.4.0-RC00
> cd ..
> git clone https://github.com/CNugteren/CLBlast.git
> cd CLBlast/
> git checkout tags/1.4.0
> mkdir build && cd build
> cmake ..
> make
> sudo make install
> cd ../../JOCLBlast/
> mkdir -p nativeLibraries/apple/x86_64
> cp ../CLBlast/build/libclblast.dylib nativeLibraries/apple/x86_64/libclblast.dylib
> cmake -DCLBlast_LIBRARY:FILEPATH=/usr/local/lib/libclblast.dylib -DCLBLAST_INSTALL_DIR:FILEPATH=/usr/local/lib/
> cmake --build .
> mvn clean install

**Comment by CNugteren** [comment] 2018-08-22 21:11
By the way, is it not a good idea to use Travis/AppVeyor to do these builds for us automatically?

**Comment by blueberry** [comment] 2018-08-25 09:03
@gpu Here is the Linux version. Finally the release is ready. Sorry for the delay. I'll see to do the 1.4.1 build as soon as you make it ready, since now the process is fresh in my head :)

[jocl-blast-1.4.0-SNAPSHOT.zip](https://github.com/gpu/JOCLBlast/files/2320500/jocl-blast-1.4.0-SNAPSHOT.zip)

**Comment by gpu** [comment] 2018-08-25 12:59
Thanks for the contributions! 

@milikicn Good to hear that the build process worked for you (although, I never really understood the details behind #13 in depth, and could not (yet) allocate enough time to investigate it). Maybe I'll take your summary as a template for instructions or a build shell script.

Could you also provide the `libclblast.dylib`? It will be part of the release, as the JOCLBlast native library refers to the CLBlast native library.


@CNugteren Setting up automated builds for as many of my libraries as possible is certainly on my TODO list (and admittedly: the manual builds in the meantime certainly outweigh the time that I did *not* yet invest for setting up the automated build :-/ ). Maybe I can tackle this after the 1.4.1 release...

**Comment by milikicn** [comment] 2018-08-25 19:19
@gpu here you go
[libclblast.dylib.zip](https://github.com/gpu/JOCLBlast/files/2320963/libclblast.dylib.zip)

**Comment by blueberry** [comment] 2018-08-25 19:20
@milikicn Does the build still link to brew's libclblast or now it works when you remove it from brew?

**Comment by milikicn** [comment] 2018-08-25 19:27
No, I don't have it in my brew repository (like I did the last time). I think the last time I missed to call "sudo make install".

**Comment by blueberry** [comment] 2018-08-25 19:28
Cool! So now that part of the build has been fixed!

**Comment by gpu** [comment] 2018-08-29 12:32
Umm... sorry @milikicn : Is that actually a ZIP file, or did you just rename it for uploading? I can only "open" it with 7zip (not WinRAR or the Explorer), and it seems to contain only gibberish.

If it's safe to just remove the `.zip` extension, just drop me a note (I'd like to avoid having an invalid release, and cannot test the library here...)

**Comment by milikicn** [comment] 2018-08-29 12:34
Just drop the zip extension, sorry for the confusion.

**Comment by gpu** [comment] 2018-08-31 16:06
Version 1.4.0 will soon be available in Maven Central.

Thanks @blueberry  and @milikicn  for contributing the native libraries!

I'll do the update to 1.4.1 ASAP and drop you a note here when it's ready.

**Comment by gpu** [comment] 2018-09-03 13:10
@blueberry @milikicn  The RC for 1.4.1 is at https://github.com/gpu/JOCLBlast/releases/tag/1.4.1-RC00

There have been no API changes, so this looks like only the version number was updated, but I think it's good to have matching versions, and a dedicated release with the 1.4.1 binary of CLBLast.

**Comment by milikicn** [comment] 2018-09-03 13:14
Sorry, but I won't be able to do this before September 12, I am away
without my computer.


Nikola

**Comment by blueberry** [comment] 2018-09-03 19:31
Here is the linux build of 1.4.1. I tried it with Neanderthal as always and all tests pass.
[jocl-blast-1.4.1-SNAPSHOT.zip](https://github.com/gpu/JOCLBlast/files/2346449/jocl-blast-1.4.1-SNAPSHOT.zip)

**Comment by milikicn** [comment] 2018-09-11 12:02
Hi @gpu , here is the OS X build. Sorry for the delay.
[jocl-blast-1.4.1-SNAPSHOT.zip](https://github.com/gpu/JOCLBlast/files/2370840/jocl-blast-1.4.1-SNAPSHOT.zip)

**Comment by gpu** [comment] 2018-09-12 15:41
No problem with the delay, I'm going to do the release ASAP and drop a note here as usual (it might also take a few days, but maybe I can manage to do it earlier)

**Comment by gpu** [comment] 2018-09-16 12:47
Version 1.4.1 is available in Maven Central:
```
<dependency>
    <groupId>org.jocl</groupId>
    <artifactId>jocl-blast</artifactId>
    <version>1.4.1</version>
</dependency>
```
Thanks again @blueberry and @milikicn and @CNugteren !

**Closed as completed by gpu** 2018-09-16 12:47 UTC
